name: FluxoEnviroments
on:
  #push:
    #branches: [ "main" ]
    
  workflow_dispatch:
jobs:  
  build:   
    runs-on: ubuntu-latest
    steps:
     - name: dev
       run: echo hello, world!
       
  deploy-dev:   
    runs-on: ubuntu-latest
    environment: 
      name: developer
     
    needs: build  
    steps:
     - name: dev
       run: echo estou no developer
       
  deploy-homolog:   
    runs-on: ubuntu-latest
    environment: 
      name: homolog
      url: 'http://www.google.com'
    needs: deploy-dev  
    steps:
     - name: homolog
       run: echo estou na homologacao
   
  deploy-prod:   
    runs-on: ubuntu-latest
    environment: 
      name: prod
      
    needs: deploy-homolog  
    steps:
     - name: producao
       run: echo estou na producção
