name: FluxoEnviroments
on:
  workflow_dispatch:

jobs:  
  build:   
    runs-on: ubuntu-latest
    steps:
     - name: dev
       run: echo hello, world!
       
  deploy-dev:   
    runs-on: ubuntu-latest
    environment: 
      name: developer
      url: "www.google.com"
    needs: build  
    steps:
     - name: dev
       run: echo estou no developer
       
  deploy-homolog:   
    runs-on: ubuntu-latest
    environment: 
      name: homolog
      url: 'www.google.com'
    needs: deploy-dev  
    steps:
     - name: homolog
       run: echo estou na homologacao
   
  deploy-prod:   
    runs-on: ubuntu-lat est
    environment: 
      name: prod
      url: 'google.com'
    needs: deploy-homolog  
    steps:
     - name: producao
       run: echo estou na producção
